In [1]:
def calculer_cout_global(cout_variable, cout_unitaire, nombre_produit):
    """
    Calcule le coût global à partir du coût variable, du coût unitaire et du nombre de produits.
    
    Arguments :
    cout_variable (float) : Le coût variable fixe.
    cout_unitaire (float) : Le coût unitaire par produit.
    nombre_produit (int) : Le nombre de produits fabriqués.
    
    Retourne :
    float : Le coût global.
    """
    # Calcul du coût global
    cout_global = cout_variable + (cout_unitaire * nombre_produit)
    return cout_global

# Exemple d'utilisation
cout_variable = 500.0
cout_unitaire = 10.0
nombre_produit = 50

cout_total = calculer_cout_global(cout_variable, cout_unitaire, nombre_produit)
print(f"Le coût global est de {cout_total:.2f} €")

Le coût global est de 1000.00 €


In [12]:
import numpy as np

matrice = np.array([[10, 5], 
                    [-4, 1]])
vecteur = np.array([[9000], 
                    [50]])

print("Matrice :")
print(matrice)
print("\nVecteur :")
print(vecteur)

Matrice :
[[10  5]
 [-4  1]]

Vecteur :
[[9000]
 [  50]]


In [13]:
from numpy.linalg import inv
inv(matrice)

array([[ 0.03333333, -0.16666667],
       [ 0.13333333,  0.33333333]])

In [14]:
np.dot(matrice,vecteur)

array([[ 90250],
       [-35950]])

In [28]:
import numpy as np

# Fonction pour générer une matrice aléatoire
def generer_matrice_aleatoire(lignes, colonnes, min_val=1, max_val=10):

    return np.random.randint(min_val, max_val + 1, size=(lignes, colonnes))

# Boucle pour générer plusieurs matrices
nombre_matrices = 5  # Nombre de matrices à générer
for i in range(nombre_matrices):
    lignes = np.random.randint(1, 5)  # Nombre de lignes entre 1 et 4
    colonnes = np.random.randint(1, 2)  # Nombre de colonnes entre 1 et 2
    matrice = generer_matrice_aleatoire(lignes, colonnes)
    print(f"Matrice aléatoire {i + 1} ({lignes}x{colonnes}):")
    print(matrice)
    print("-" * 30)

Matrice aléatoire 1 (4x1):
[[1]
 [3]
 [6]
 [1]]
------------------------------
Matrice aléatoire 2 (2x1):
[[8]
 [8]]
------------------------------
Matrice aléatoire 3 (3x1):
[[1]
 [7]
 [8]]
------------------------------
Matrice aléatoire 4 (1x1):
[[6]]
------------------------------
Matrice aléatoire 5 (3x1):
[[ 5]
 [10]
 [ 4]]
------------------------------


In [29]:
import numpy as np
from numpy.linalg import LinAlgError, det

def verifier_et_donner_solution(A, b):
    """
    Vérifie si le système A * x = b a une solution unique et renvoie cette solution.
    
    Arguments :
    A : numpy.ndarray : Matrice des coefficients (carrée pour une solution unique).
    b : numpy.ndarray : Vecteur des termes constants.
    
    Retourne :
    str : La solution si elle existe, ou un message indiquant l'absence de solution.
    """
    # Vérification que la matrice A est carrée
    if A.shape[0] != A.shape[1]:
        return "La matrice A doit être carrée pour garantir une solution unique."
    
    # Vérification si la matrice A est inversible
    if det(A) == 0:
        return "La matrice A n'est pas inversible. Le système n'a pas de solution unique."
    
    # Résolution du système
    try:
        solution = np.linalg.solve(A, b)
        return f"La solution unique est : {solution}"
    except LinAlgError:
        return "Erreur lors de la résolution du système."

# Générer et tester des matrices aléatoires
def tester_matrices_aleatoires(nombre_matrices, taille_matrice):
    """
    Génère et teste des systèmes aléatoires A * x = b.
    
    Arguments :
    nombre_matrices (int) : Nombre de systèmes à générer.
    taille_matrice (int) : Taille des matrices carrées (n x n).
    """
    for i in range(nombre_matrices):
        # Générer une matrice aléatoire carrée et un vecteur aléatoire
        A = np.random.randint(-10, 10, size=(taille_matrice, taille_matrice))
        b = np.random.randint(-10, 10, size=taille_matrice)
        
        print(f"Test {i + 1} :")
        print("Matrice A :")
        print(A)
        print("Vecteur b :")
        print(b)
        
        resultat = verifier_et_donner_solution(A, b)
        print(resultat)
        print("-" * 50)

# Exemple d'utilisation
tester_matrices_aleatoires(nombre_matrices=5, taille_matrice=3)

Test 1 :
Matrice A :
[[  1   3   3]
 [-10  -3   2]
 [  5   9   1]]
Vecteur b :
[-1 -8  9]
La solution unique est : [ 0.19354839  1.05376344 -1.4516129 ]
--------------------------------------------------
Test 2 :
Matrice A :
[[ 3  5  3]
 [-8  6  5]
 [ 0  4 -3]]
Vecteur b :
[-6 -9 -7]
La solution unique est : [ 0.19393939 -1.50909091  0.32121212]
--------------------------------------------------
Test 3 :
Matrice A :
[[ -7  -1 -10]
 [  8  -5   3]
 [  9  -6  -8]]
Vecteur b :
[0 3 8]
La solution unique est : [ 0.5738758   0.07280514 -0.40899358]
--------------------------------------------------
Test 4 :
Matrice A :
[[  9  -4 -10]
 [ -7   1  -1]
 [ -4  -8   5]]
Vecteur b :
[ 4 -8  6]
La solution unique est : [ 0.92975734 -0.75351213  0.73818646]
--------------------------------------------------
Test 5 :
Matrice A :
[[ -9   3  -5]
 [ -4 -10   3]
 [ -5  -9 -10]]
Vecteur b :
[-2 -1 -8]
La solution unique est : [0.00080775 0.26736672 0.55896607]
----------------------------------------------

In [31]:
import numpy as np
from numpy.linalg import det

def calculer_determinants_aleatoires(nombre_matrices, taille_matrice):
    """
    Génère des matrices carrées aléatoires et calcule leur déterminant.
    
    Arguments :
    nombre_matrices (int) : Nombre de matrices à générer.
    taille_matrice (int) : Taille des matrices carrées (n x n).
    
    Retourne :
    Une liste contenant les déterminants des matrices générées.
    """
    determinants = []
    for _ in range(nombre_matrices):
        A = np.random.randint(-10, 10, size=(taille_matrice, taille_matrice))
        determinants.append(det(A))
    return determinants

# Exemple d'utilisation
resultats = calculer_determinants_aleatoires(nombre_matrices=5, taille_matrice=3)
print(resultats)

[-14.000000000000016, -331.9999999999999, 412.9999999999998, 99.99999999999996, 243.99999999999986]


In [ ]:
matrice_solve_a = np.array([[1, 2, -1, 3, 2], 
                          [2, -1, 3, -1, 1]
                          [-1, 3, 2, 2, -3]
                         [1, -1, 1, 2, 3]
                         [1, 4, -1, 3, 1]])

matrice_solve_b = np.array([[8, 15, 7, 20, 5]])